### ISSUE TITLE
Would it be possible to add a line of code to make it run off of a local uploaded file (like a rom in file explorer)?

### ISSUE THREAD

**Issue by BypassGoGuardianPLS** [e9x/ruffle-example#1]

**Comment by e9x** [comment]
Yes. You can create a blob URI by retrieving the data uploaded through a `<input type="file">` element. I can provide an example if needed.

**Comment by maddox05** [comment]
Just link it like you would any other file swfobject.embedSWF("../assets/games/raftwars.swf"
