### ISSUE TITLE
We Need An Updated Version

### ISSUE THREAD

**Issue by TheOriginalRagdev** [e9x/ruffle-example#2]
This version of Ruffle Swf Player is not compatible with ActionScript 3, A lot of flash games use ActionScript 3 though. If we could get an updated version, that would be cool! (Ruffle does indeed run ActionScript 3 now!)

**Comment by maddox05** [comment]
Hi! I have implemented a newer version before on my site and now that AS3 is working ill add that version on my site [duckmath](https://github.com/duckmath/duckmath.github.io). I will get a working version of that there or if you need more help message me.

**Comment by e9x** [comment]
Solved in #4
